/* MP object keys. Must be synchronized with supervisor. */

#define APS00_SANDBOX_APS_CAMERA_ASMPKEY_MQ    2
#define APS00_SANDBOX_APS_CAMERA_ASMPKEY_MUTEX 3

#define APS00_SANDBOX_APS_CAMERA_ASMPKEY_SHM    10

#define MSG_ID_APS00_SANDBOX_APS_CAMERA_ASMP 1
#define MSG_ID_APS00_SANDBOX_APS_CAMERA_EXIT 3

#define SHMSIZE_IMAGE_YUV_SIZE  (320*240*2)
#define SHMSIZE_IMAGE_RGB_SIZE  (320*240*2)
