/* MP object keys. Must be synchronized with supervisor. */

#define APS00_SANDBOX_APS_MULTICOREKEY_SHM   1
#define APS00_SANDBOX_APS_MULTICOREKEY_MQ    2
#define APS00_SANDBOX_APS_MULTICOREKEY_MUTEX 3

#define MSG_ID_APS00_SANDBOX_APS_MULTICORE 1
